### ISSUE TITLE
Zahlen raten

### ISSUE THREAD

**Issue by voxain** [dev-schueppchen/programmier-aufgaben#1]
Man generiert eine zufällige Zahl zwischen 1 und 100, der Spieler muss diese dann erraten.

Ist die eingegebene Zahl zu hoch oder zu niedrig, wird eine entspr. Meldung ausgegeben.

*Zusatzaufgaben:*
* Man kann sich den Bereich der generierten Zahl aussuchen, bspw. 5 bis 30.
* Nach x Fehlversuchen wird eine kleine Hilfestellung gegeben, bspw.nach 5 falschen Versuchen: "Die Zahl liegt zwischen x und y".

**Comment by Ron31** [comment]
Was für eine Schwierigkeit?

**Comment by voxain** [comment]
Mittel
