### ISSUE TITLE
Trivia-Quiz

### ISSUE THREAD

**Issue by voxain** [dev-schueppchen/programmier-aufgaben#2]
Der Benutzer bekommt nacheinander verschiedene Fragen gestellt, zu denen er eine richtige Antwort geben muss.
Für jede richtige Antwort gibt es einen Punkt.

*Zusatzaufgaben:*
* Nach x Fehlversuchen bekommt man Antwortmöglichkeiten vorgegeben.
* Die Fragen werden aus einer Datei geladen, jeder kann neue hinzufügen.
* Gibt man sofort die richtige Antwort, bekommt man 3 Punkte. Bei falscher Antwort hat man noch x Versuche, bekommt dafür aber weniger Punkte.

**Comment by Ron31** [comment]
Was für eine Schwierigkeit?

**Comment by voxain** [comment]
Würde sagen einfach
